from .database import load_tables

_TABLES = load_tables()
WIRE_DB = _TABLES["tables"]["WIRE_DB"]
PIPE_DB = _TABLES["tables"]["PIPE_DB"]
HVAC_PIPES = _TABLES["tables"]["HVAC_PIPES"]
NFB_SIZES = _TABLES["tables"]["NFB_SIZES"]
VOLTAGE_MAP = _TABLES["tables"]["VOLTAGE_MAP"]
GAS_DESIGN_VELOCITY_MPS = _TABLES["tables"]["GAS_DESIGN_VELOCITY_MPS"]
CLEANROOM_DB = _TABLES["tables"]["CLEANROOM_DB"]
ORIGINAL_DEFAULTS = {
    "sys_type": "AHU (OA+RA 混合)",
    "rt_type": "US RT (美制 3024 kcal/hr)",
    "c_a": "Class 1,000",
    "c_b": "無 (None)",
    "en_ach_A": "70",
    "en_ach_B": "0",
    "en_p_A": "15",
    "en_p_B": "0",
    "oa_t": "35",
    "oa_rh": "70",
    "ra_t": "22",
    "ra_rh": "50",
    "chw_in": "7.0",
    "coil_approach": "4.5",
    "en_L_A": "40",
    "en_W_A": "25",
    "en_H_A": "3.5",
    "en_L_B": "0",
    "en_W_B": "0",
    "en_H_B": "3.5",
    "en_gap_L": "18.0",
    "en_gap_W": "0.01",
    "en_door_A": "5.04",
    "en_door_F": "2",
    "prd_q": "500",
    "en_manual_oa": "0",
    "ppl_A": "100",
    "ppl_B": "0",
    "light_qty": "480",
    "light_w": "40",
    "en_wall": "455",
    "en_floor": "1000",
    "process_latent_kw": "5.0",
    "eq_kw": "1500",
    "eq_rt": "90",
    "exh_ratio": "10",
    "oven_kw": "0",
    "sf": "10",
    "pcw_n": "50",
    "pcw_lpm": "30",
    "pcw_dt": "5.0",
    "gas1_type": "N2",
    "gas1_q": "500",
    "gas2_type": "CDA",
    "gas2_q": "800",
    "gas3_type": "O2",
    "gas3_q": "0",
    "gas_barg": "6.0",
    "pv_q": "2000",
    "pv_torr": "150",
    "v_pv_mat": "SUS白鐵管",
    "e_volt": "3Φ4W 380/220V",
    "e_pf": "0.85",
    "e_eff": "0.90",
    "e_wire": "XLPE 絕緣電纜 (90°C)",
    "e_temp": "35℃ 以下 (標準)",
    "e_pipe": "3根以下 (標準)",
    "e_up_type": "一般負載",
    "e_up_kw": "135.0",
    "e_up_hp": "0.0",
    "e_up_oven": "20.0",
    "e_np_type": "連續負載",
    "e_np_fan": "25.0",
    "u_e_np_fan": "kW",
    "e_np_heat": "0.0",
    "u_e_np_heat": "kW",
    "e_np_humid": "5.0",
    "u_e_np_humid": "kW",
    "e_np_exh": "10.0",
    "u_e_np_exh": "kW",
    "e_np_pump": "15.0",
    "gex_q": "0",
    "u_gex": "CMH",
    "sex_q": "0",
    "u_sex": "CMH",
    "aex_q": "0",
    "u_aex": "CMH",
    "vex_q": "0",
    "u_vex": "CMH",
    "hex_q": "0",
    "u_hex": "CMH",
    "v_gex": "12.0",
    "v_sex": "10.0",
    "v_vex": "12.0",
    "duct_ratio": "1.5",
    "chw_q": "400",
    "u_chw": "LPM",
    "dt_chw": "5.0",
    "dccw_q": "250",
    "u_dccw": "LPM",
    "dt_dccw": "4.0",
    "pcw_tot": "380",
    "u_pcw_tot": "LPM",
    "dt_pcw_sys": "5.0",
    "hw_q": "100",
    "u_hw": "LPM",
    "dt_hw": "10.0",
    "upw_type": "UPW (超純水)",
    "upw_q": "100",
    "upw_v": "1.2",
    "upw_mat": "PVDF (超純水專用)",
    "upw_res": "18.2 MΩ·cm",
    "upw_toc": "< 1 ppb",
    "upw_do": "< 1 ppb",
    "upw_temp": "25 ± 0.1",
}
V31_DEFAULTS = {
    "sys_type": "MAU+FFU+DCC (全外氣/無塵室)",
    "rt_type": "US RT (美制 3024 kcal/hr)",
    "c_a": "Class 1,000",
    "c_b": "無 (None)",
    "en_ach_A": "70",
    "en_ach_B": "0",
    "en_p_A": "15",
    "en_p_B": "0",
    "oa_t": "35",
    "oa_rh": "70",
    "ow_t": "8",
    "ow_rh": "70",
    "ra_t": "22",
    "ra_rh": "50",
    "chw1_in": "12.0",
    "pre_t": "26.0",
    "pre_rh": "80",
    "chw2_in": "7.0",
    "coil_approach": "4.5",
    "dccw_in": "14.0",
    "en_dcc_rt": "3.4",
    "en_fcu_cmh": "1200",
    "en_rcu_rt": "30",
    "en_L_A": "40",
    "en_W_A": "25",
    "en_H_A": "3.5",
    "en_L_B": "0",
    "en_W_B": "0",
    "en_H_B": "3.5",
    "en_gap_L": "18.0",
    "en_gap_W": "0.01",
    "en_door_A": "5.04",
    "en_door_F": "2",
    "prd_q": "500",
    "en_manual_oa": "0",
    "ppl_A": "100",
    "ppl_B": "0",
    "light_lux": "600",
    "light_lm": "2000",
    "light_w": "40",
    "light_u": "0.6",
    "light_m": "0.8",
    "en_wall": "455",
    "en_floor": "1000",
    "process_latent_kw": "5.0",
    "eq_kw": "1500",
    "eq_rt": "90",
    "exh_ratio": "10",
    "oven_kw": "0",
    "sf": "10",
    "pcw_n": "50",
    "pcw_lpm": "30",
    "pcw_dt": "5.0",
    "gas1_type": "N2",
    "gas1_q": "500",
    "u_gas1": "SLPM",
    "gas2_type": "CDA",
    "gas2_q": "800",
    "u_gas2": "SLPM",
    "gas3_type": "O2",
    "gas3_q": "0",
    "u_gas3": "SLPM",
    "gas_barg": "6.0",
    "pv_q": "2000",
    "u_pv": "SLPM",
    "pv_torr": "150",
    "v_pv_mat": "SUS白鐵管",
    "e_volt": "3Φ4W 380/220V",
    "e_pf": "0.85",
    "e_eff": "0.90",
    "e_wire": "XLPE 絕緣電纜 (90°C)",
    "e_temp": "35℃ 以下 (標準)",
    "e_pipe": "3根以下 (標準)",
    "e_up_type": "一般負載",
    "e_up_eq": "135.0",
    "u_e_up_eq": "kW",
    "e_up_oven": "20.0",
    "u_e_up_oven": "kW",
    "e_np_type": "連續負載",
    "e_np_fan": "25.0",
    "u_e_np_fan": "kW",
    "e_np_heat": "0.0",
    "u_e_np_heat": "kW",
    "e_np_humid": "5.0",
    "u_e_np_humid": "kW",
    "e_np_exh": "10.0",
    "u_e_np_exh": "kW",
    "e_np_pump": "15.0",
    "u_e_np_pump": "kW",
    "gex_q": "0",
    "u_gex": "CMH",
    "sex_q": "0",
    "u_sex": "CMH",
    "aex_q": "0",
    "u_aex": "CMH",
    "vex_q": "0",
    "u_vex": "CMH",
    "hex_q": "0",
    "u_hex": "CMH",
    "v_gex": "12.0",
    "v_sex": "10.0",
    "v_vex": "12.0",
    "duct_ratio": "1.5",
    "chw_q": "400",
    "u_chw": "LPM",
    "dt_chw": "5.0",
    "dccw_q": "250",
    "u_dccw": "LPM",
    "dt_dccw": "4.0",
    "pcw_tot": "380",
    "u_pcw_tot": "LPM",
    "dt_pcw_sys": "5.0",
    "hw_q": "100",
    "u_hw": "LPM",
    "dt_hw": "10.0",
    "upw_type": "UPW (超純水)",
    "upw_q": "100",
    "upw_v": "1.2",
    "upw_mat": "PVDF (超純水專用)",
    "upw_res": "18.2 MΩ·cm",
    "upw_toc": "< 1 ppb",
    "upw_do": "< 1 ppb",
    "upw_temp": "25 ± 0.1",
}
